name: ✨ Feature request
description: Suggest a new feature or improvement
title: '[Feature Request]: '
labels: [enhancement, no-priority]

body:
- type: markdown
  attributes:
    value: >
      Thanks for suggesting a feature!
      
      - Please search the existing feature request to see if there has been a similar issue filed.
      
      - If a feature has been filed before, but not followed up by a contributor, you can develop the feature yourself.
      
      - Repeat feature requests are allowed if the previous request has been closed for more than 30 days
      
      - drive-by feature requests without effort will be closed.
      
- type: textarea
  attributes:
    label: Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.
  validations:
    required: true
- type: textarea
  attributes:
    label: PowerShell commands you would normally use to achieve above request
  validations:
    required: false
