name: Publish New Version

on:
  push:
    tags: '*'

jobs:
  publish:   
    name: Publish 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: PowerShell script
        uses: Amadevus/pwsh-script@v2.0.3
        id: Build-Module
        with:
          script: | 
            Install-Module ModuleBuilder -Force
            Build-Module -SemVer ${{ github.ref_name }}

      - name: Publish PowerShell Module
        uses: pcgeek86/publish-powershell-module-action@v20
        with:
          modulePath: .\Output\CIPPAPIModule
          NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}
